### ISSUE TITLE
Default SA

### ISSUE THREAD

**Issue by RichardScottOZ** [Loop3D/Loop3D#2]
Hi, downloaded to give it a shot, thought I would try the default SA possibility.

Ended up with a raster memory error perhaps?  I haven't looked into it at all yet.

![LoopGUICapture](https://user-images.githubusercontent.com/72196131/114293298-2043f180-9ad4-11eb-98dd-68d719917cd6.PNG)

**Comment by markjessell** [comment]
Hi Richard

Thanks, I have forward to Roy who looks after the GUI version...

Cheers

mark

From: RichardScottOZ ***@***.***>
Sent: Sunday, 11 April 2021 1:13 PM
To: Loop3D/Loop3D ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Loop3D/Loop3D] Default SA (#2)


Hi, downloaded to give it a shot, thought I would try the default SA possibility.

Ended up with a raster memory error perhaps? I haven't looked into it at all yet.

[LoopGUICapture]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F72196131%2F114293298-2043f180-9ad4-11eb-98dd-68d719917cd6.PNG&data=04%7C01%7Cmark.jessell%40uwa.edu.au%7C3945395ce1964cd55d8b08d8fca873b3%7C05894af0cb2846d8871674cdb46e2226%7C1%7C0%7C637537147718402521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xqxxZ2o7bh%2FV%2BCKC2huBgZAMi8jQQYzHwsq%2BRS%2FA5Tk%3D&reserved=0>

-

**Comment by RoyThomsonMonash** [comment]
In the first release (0.1.0), the SA dataset had not been fully integrated.  I have since got the SA example working and will have a new release on the loop website later this week or early next week (once I have finished some further testing).

**Comment by RichardScottOZ** [comment]
Thanks Roy.  I will remove it and wait for your update then.

**Comment by RoyThomsonMonash** [comment]
The new release on the loop3d website has SA working correctly.

**Comment by RichardScottOZ** [comment]
Thanks Roy, I will check it out shortly.
