### ISSUE TITLE
Orientations missing

### ISSUE THREAD

**Issue by RichardScottOZ** [Loop3D/Loop3D#3]
``` python
Loop: Loading python source file  "processMap2Loop.py"
Loop: Loading python source file  "processLoopStructural.py"
Loop: Opening data source configuration file  "DataSource.conf"
Starting Loop GUI ...
Model size of -22 is less than 0
LoopProjectFile:  No structural model in loop project file
Saving to file  "file:///H:/Loop3D-v0.1.1/Loop3D/satest.loop3d"
Loop: Loading python script file named:  "H:/Loop3D-v0.1.1/Loop3D/satest.loop3d"
Running Map2Loop Python Script
structure =  http://geo.loop-gis.org/geoserver/GSSA/wfs
geology   =  http://geo.loop-gis.org/geoserver/GSSA/wfs
mindep    =
fault     =  http://geo.loop-gis.org/geoserver/GSSA/wfs
fold      =  http://geo.loop-gis.org/geoserver/GSSA/wfs
meta      =  source_data/sa/sa_meta.hjson
Using: ps
MAP2LOOP Project init took 0 minutes and 6 seconds
PythonError:
Traceback (most recent call last):
  File "<string>", line 91, in threadFunc
  File "H:\Loop3D-v0.1.1\Loop3D\pythonEnv\lib\site-packages\map2loop\project.py", line 328, in update_config
    self.config = Config(out_dir, overwrite, self.geology_file,
  File "H:\Loop3D-v0.1.1\Loop3D\pythonEnv\lib\site-packages\map2loop\config.py", line 136, in __init__
    structure_file, geology_file, fault_file, mindep_file, fold_file, c_l = m2l_map_checker.check_map(
  File "H:\Loop3D-v0.1.1\Loop3D\pythonEnv\lib\site-packages\map2loop\m2l_map_checker.py", line 387, in check_map
    raise NameError(sep.join(m2l_errors) +
NameError: not enough orientations to complete calculations (need at least 2), projection may be inconsistent
 map2loop error: Fix errors before running again
```

**Comment by RichardScottOZ** [comment]
I picked an area (geodetic) - a 1degree box basically, hit extract data - it brought me to a file save, which I did for the project and it closed.

Then I reran - and loaded and did extract data.

**Comment by RichardScottOZ** [comment]
![Loop3DcaptureCapture](https://user-images.githubusercontent.com/72196131/115984873-5612cb00-a5e8-11eb-8be6-5f65a1226b5c.PNG)

**Comment by markjessell** [comment]
Hi Richard
From what I can see I am guessing you have selected a region of interest with no bedding information, hence the error message?

Cheers
Mark

Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E ***@***.***

________________________________

**Comment by markjessell** [comment]
It is on the list to add the outcrops to the map in the GUI version as we have in the notebooks.

M

Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E ***@***.***

________________________________

**Comment by RichardScottOZ** [comment]
Ok, thanks...likely lots of them from memory..so should make some up to test it?

**Comment by markjessell** [comment]
There probably are, but if this is GSSA data, they don’t have an online outcrop database server so we are limited to the data they send me on an ad hoc basis, hence the need to have the outcrops show on the map! The area you chose does all seems to be the same strat unit so I am not sure how you would build a model in any case?

M

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
